domodwyer/mailyak

- writer.go
- writer_test.go
Multiple successive calls to a BodyPart would overwrite the previous contents. Users of MailYak should not be forced to write a BodyPart in one go – when using different templating engines this becomes a real problem because users don’t have any way to influence the write behavior.
Still, a better way would be to just use a plain `bytes.Buffer` as the base (or instead of) the `BodyPart` implementation. When looking at the standard lib's implementation of `bytes.Buffer` (https://golang.org/src/bytes/buffer.go) one can see that it more gracefully handles growing buffers and GC pressure, has better efficiency and also uses a plain byte slice as the workhorse (like `BodyPart`). I have an implementation of that in a separate branch if you want to take a look.
I updated a single test case but …
> Fix multiple writes to a BodyPart overwriting previous contents

- attachments.go
- mailyak.go
- mime.go
Several methods were not pointer receivers and I don't see why – not having them is prone to copy around a lot of objects. Did you have a good reason to not add them?
> Add missing pointer receivers

- mailyak.go
- mailyak_test.go
I also added a test and made sure that no auth credentials are leaked when this is used to log a mail object via a logger.
> Make MailYak struct conform to the Stringer interface

- mailyak.go
- mime.go
- mime_test.go
- package.go
- writer.go
- writer_test.go
Also, the body parts embedded by value are ready to be used – don’t muck around with manual creation of these internal struct fields, just use the public API.
> Use a byte buffer as the `BodyPart` storage

- mailyak.go
- mime.go
Hi @domodwyer ,
First of all, thanks for your package. This is exactly what I needed, although for a different purpose.
I am mainly interested in the MIME data you generate and not so much sending the emails via SMTP.
We use Amazon SES to send our e-mails and use the Raw MIME sending function.
(See http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html#send-email-raw-mime )
I currently don't see a way to access the MIME data we need to send, so my proposal is to add a method on MailYak which returns the mime buffer you create before sending.
This is a pull request which does exactly that, I have just tested this on my fork and it works perfectly for AWS SES, so it will probably work for similar services as well. I think this will help a lot of people sending MIME …
> Proposal: Add method to get the raw MIME data

- mailyak.go
- mime.go
- mime_test.go
- setters.go
This PR is intended to fix issue #14.
It adds a new setter on the mailyak object to control wether or not bcc headers should be written.
```
mail.WriteBccHeader(false)
```
Default value is set to `true` to always write bcc headers and so, do not change the current behavior.
Unit tests have been done on the `writeHeaders` method, and manual checking have been done using reported issue example:
* If `WriteBccHeader` is set to true, all recipients will see the headers
* Otherwise, "Bcc recipients" do not see each other and "To" recipients do not see "Bcc" addresses
> Added an opt-in flag to optionally include bcc headers

- attachments.go
- attachments_test.go
- mime_test.go
As stated in the title, this PR adds in support for spaces in attachment filenames. 
I was writing a library to send emails through AWS SES earlier today, using Mailyak to create the raw MIME messages, and tried sending an email with an attachment that had a space in the filename, when I discovered that this resulted in an error occurring. After some googling I found that others usually suggest to quote the filename in MIME headers, and when I fixed that in my own fork I saw that I could now correctly send emails with such attachments.
> Add support for spaces in attachment filenames

- mailyak.go
Hi.
I realized a problem as below and considered a solution.
I sent a mail by [sendgrid's](https://sendgrid.com/) smtp server.
That mail contains one `to` address and one `cc` address, and of course delivered to the `to` address but not delivered to the `cc` address.
(I tried by [mailjet](https://www.mailjet.com/) also, and got same result.)
**code**
```
host := "smtp.sendgrid.net"
auth := smtp.PlainAuth("", "apikey", os.Getenv("SENDGRID_APIKEY"), host)
m := mailyak.New(host+":2525", auth)
m.Subject("blah blah blah")
m.From("noreply@mfkessai.co.jp")
m.To("suzuki.shintaro@mfkessai.co.jp")
m.Cc("makiton@gmail.com") // not delivered... why?
m.Plain().Set("hoge hoge hoge\nhogehoge")
if err := m.Send(); err != nil {
fmt.Errorf(err.Error())
}
```
I used …
> Send ccAddrs to the smtp server as RCPT TO addresses

- attachments.go
- attachments_test.go
- mime_test.go
Adds the attachWithMimeType dicussed in https://github.com/domodwyer/mailyak/issues/25 and also added a AttachInlineWithMimeType for parity.
Testing wise the new field in the attachment struct I defaulted to "" in a bunch of tests because its not important.  I added in 2 tests very similar to the existing ones that test the attachment slice length, I also added cases to the write attachments / write inline attachments tests to ensure the specified mime is being set.
I thought it would be handy on the original attach funcs to note in the comments how they handle the mime type given its quite important / to save digging around in the code.
> Add ability to attach files with specified mime types

- mime.go
- mime_test.go
Sometimes the lines of the body are too long and leads to malformed mails in the clients.
This happens with the framework Foundations emails 2 and its HTML minifier.
The body must be encoded with quoted printable.
Signed-off-by: Cyril GY <cyril.gy@gmail.com>
> Email body should be encoded as 'quoted-printable'

- attachments.go
This change set **Content-ID** same way for Inline and Non Inline Attachments, and should resolve #44
> #44 Add Content-ID for Inlined Attachments

- go.mod
Go modules require the major version to be added to the end of the
module path after version 2:
the go command requires that modules with major version v2 or later
use a module path with that major version as the final element
https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
Fixes #46
> mod: specify version in import path

- mailyak.go
- mailyak_test.go
As discussed in
https://github.com/domodwyer/mailyak/issues/50#issuecomment-720597806
the library should automatically updated the date timestamp before
sending out emails, otherwise re-using the MailYak instance (over
longer periods of time) leads to stale timestamps.
With this patch, the timestamp is automatically updated in Send() and
MimeBuf() methods. It also adds a testcase for this scenario.
Closes #50
> Update 'Date' timestamp before sending email

- integration_test.go
- mailyak_test.go
- mime.go
- mime_test.go
Changes the MIME generation code to always include the "Content-Type"
header in each of the the MIME parts, even if the part is empty.
Previously an empty plain text or HTML body could cause some SMTP
servers to reject the mail due to the missing headers. Emails that
included both HTML and plain-text conent were not affected.
Fixes #61.
> fix: include content type in empty MIME parts

- mime.go
- mime_test.go
Instead of writing (empty) MIME parts, don't write alternatives at all in empty mails.
This should still preserve the correct display in mail clients. The 'empty file' error described in https://github.com/domodwyer/mailyak/issues/61 should still be fixed.
This should fix https://github.com/domodwyer/mailyak/issues/63.
> fix: only add html/plain parts if they actually exist

- .github/workflows/lints.yml
- attachments.go
- mailyak.go
- sender_test.go
- setters.go
Remove the golangci version pin to unblock CI.
---
* ci: bump golangci version (4d0d2d2)
* test: panic in testing goroutine (23296ca)
Panic in the test goroutines, instead of calling t.Fatal (which is racy).
* style: gofmt (c9babb3)
> ci: bump golangci version

- mime.go
- mime_test.go
This is a fix for #70.  Rather than multiple headers, it uses a comma separated list.
- modified the test cases with multiple addresses to expect comma separated lists
- verified that all tests pass
> fix: use comma separated list for To, CC, BCC headers

- .golangci.yml
- mailyak.go
- sender.go
- sender_test.go
- setters.go
- setters_test.go
Some SMTP servers, such as the Gmail SMTP-relay, requires a proper
domain name in the inital EHLO/HELO exchange and will reject attempts to
use localhost.
> feat: support setting custom sender domain

- mailyak.go
- mailyak_test.go
- mime.go
- setters.go
- setters_test.go
Allows multiple values to be set for the same header key. This is required for MailGun's X-Mailgun-Tag header if you want to set multiple categories.
> added support for multiple values for same header key

- attachments.go
- attachments_test.go
- mime_test.go
Hi, thank you for your awesome lib.
I recently found myself in a situation where I need to add an attachment to my email, and this attachment **needs** to have a header reading `name="file.txt"`
But your lib can only do `filename="file.txt"`
I'm not very confident in the way I'm handling this PR, so if you have any feedback, I can change it to anyway your prefer. I just need a way to modify this header.
I think the new variable name I introduce (attachmentFilenameHeader) is a little longer than I would like, but I can't think of anything shorter that would not be confusing. Let me know...
I did not run the static analysis lints (sorry, I don't know how to do that) so I hope this is something that is automatically checked when a PR is opened (?)
"go test" in local is OK though...
> Attachment headers are both "filename" and "name"

- mime.go
- mime_test.go
The `Mime-Version: 1.0` header is automatically added in `writeHeaders` (_mime.go_).
This however negatively affects the spam score with some email providers as the casing does not follow [RFC 1341](https://www.w3.org/Protocols/rfc1341/3_MIME-Version.html), which requires the correct header to read: `MIME-Version: 1.0` (note the uppercase `MIME`).
> fix: correct MIME-Version header casing

- mime.go
- mime_test.go
That's became a little bit more complicated that I have expected.
Certainly it is easy to fix case when we pass only attachments how it was discussed in #85, but then we will get messages more or less like this:
```
From:
Mime-Version: 1.0
Date: Tue, 18 Jul 2023 16:10:51 +0400
Subject:
To: dom@itsallbroken.com
Content-Type: multipart/mixed;
boundary="5b015828a43b39e9c393a7602b852053de3f11a4632e5acdbad189bc129f"; charset=UTF-8
--5b015828a43b39e9c393a7602b852053de3f11a4632e5acdbad189bc129f
Content-Disposition: attachment;
filename="myattachment"; name="myattachment"
Content-ID: <myattachment>
Content-Transfer-Encoding: base64
Content-Type: text/plain; charset=utf-8;
filename="myattachment"; name="myattachment"
Y29udGVudA==
--5b015828a43b39e9c393a7602b852053de3f11a4632e5acdbad189bc129f--
``` …
> fix: correct messages with empty/partially empty bodies (#85)
